# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pbinsumRow <- function(y, N, p) {
    .Call(`_nmmsims_pbinsumRow`, y, N, p)
}

pbinsum <- function(y, N, p) {
    .Call(`_nmmsims_pbinsum`, y, N, p)
}

rcpp_hello_world <- function() {
    .Call(`_nmmsims_rcpp_hello_world`)
}

